/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { SaleService } from "../sale.service";
import { SaleCreateInput } from "./SaleCreateInput";
import { Sale } from "./Sale";
import { SaleFindManyArgs } from "./SaleFindManyArgs";
import { SaleWhereUniqueInput } from "./SaleWhereUniqueInput";
import { SaleUpdateInput } from "./SaleUpdateInput";
import { SaleDetailFindManyArgs } from "../../saleDetail/base/SaleDetailFindManyArgs";
import { SaleDetail } from "../../saleDetail/base/SaleDetail";
import { SaleDetailWhereUniqueInput } from "../../saleDetail/base/SaleDetailWhereUniqueInput";

export class SaleControllerBase {
  constructor(protected readonly service: SaleService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Sale })
  async createSale(@common.Body() data: SaleCreateInput): Promise<Sale> {
    return await this.service.createSale({
      data: {
        ...data,

        customer: data.customer
          ? {
              connect: data.customer,
            }
          : undefined,
      },
      select: {
        createdAt: true,

        customer: {
          select: {
            id: true,
          },
        },

        id: true,
        note: true,
        saleDate: true,
        totalAmount: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Sale] })
  @ApiNestedQuery(SaleFindManyArgs)
  async sales(@common.Req() request: Request): Promise<Sale[]> {
    const args = plainToClass(SaleFindManyArgs, request.query);
    return this.service.sales({
      ...args,
      select: {
        createdAt: true,

        customer: {
          select: {
            id: true,
          },
        },

        id: true,
        note: true,
        saleDate: true,
        totalAmount: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Sale })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async sale(
    @common.Param() params: SaleWhereUniqueInput
  ): Promise<Sale | null> {
    const result = await this.service.sale({
      where: params,
      select: {
        createdAt: true,

        customer: {
          select: {
            id: true,
          },
        },

        id: true,
        note: true,
        saleDate: true,
        totalAmount: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Sale })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateSale(
    @common.Param() params: SaleWhereUniqueInput,
    @common.Body() data: SaleUpdateInput
  ): Promise<Sale | null> {
    try {
      return await this.service.updateSale({
        where: params,
        data: {
          ...data,

          customer: data.customer
            ? {
                connect: data.customer,
              }
            : undefined,
        },
        select: {
          createdAt: true,

          customer: {
            select: {
              id: true,
            },
          },

          id: true,
          note: true,
          saleDate: true,
          totalAmount: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Sale })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteSale(
    @common.Param() params: SaleWhereUniqueInput
  ): Promise<Sale | null> {
    try {
      return await this.service.deleteSale({
        where: params,
        select: {
          createdAt: true,

          customer: {
            select: {
              id: true,
            },
          },

          id: true,
          note: true,
          saleDate: true,
          totalAmount: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/saleDetails")
  @ApiNestedQuery(SaleDetailFindManyArgs)
  async findSaleDetails(
    @common.Req() request: Request,
    @common.Param() params: SaleWhereUniqueInput
  ): Promise<SaleDetail[]> {
    const query = plainToClass(SaleDetailFindManyArgs, request.query);
    const results = await this.service.findSaleDetails(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,

        item: {
          select: {
            id: true,
          },
        },

        quantity: true,

        sale: {
          select: {
            id: true,
          },
        },

        unitPrice: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/saleDetails")
  async connectSaleDetails(
    @common.Param() params: SaleWhereUniqueInput,
    @common.Body() body: SaleDetailWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      saleDetails: {
        connect: body,
      },
    };
    await this.service.updateSale({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/saleDetails")
  async updateSaleDetails(
    @common.Param() params: SaleWhereUniqueInput,
    @common.Body() body: SaleDetailWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      saleDetails: {
        set: body,
      },
    };
    await this.service.updateSale({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/saleDetails")
  async disconnectSaleDetails(
    @common.Param() params: SaleWhereUniqueInput,
    @common.Body() body: SaleDetailWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      saleDetails: {
        disconnect: body,
      },
    };
    await this.service.updateSale({
      where: params,
      data,
      select: { id: true },
    });
  }
}
